### ISSUE TITLE
Build latest version failed

### ISSUE THREAD

**Issue by pigass0512** [NetrisTV/ws-scrcpy#42] opened 2020-10-08 10:18 UTC
Hi @drauggres master,

After I clone the latest version(v0.5) and build the service, it failed..
Can you help to check what is the problem?
Thanks!

```
    ERROR in ./vendor/Genymobile/scrcpy/scrcpy-server.jar 1:2
    Module parse failed: Unexpected character '' (1:2)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders     
    (Source code omitted for this binary file)
     @ ./src/server/ServerDeviceConnection.ts 5:0-59
     @ ./src/server/ServiceDeviceTracker.ts
     @ ./src/server/index.ts

    ERROR in ./vendor/Genymobile/scrcpy/LICENSE.txt 2:40
    Module parse failed: Unexpected token (2:40)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders     
    |
    >                                  Apache License
    |                            Version 2.0, January 2004
    |                         http://www.apache.org/licenses/
     @ ./src/server/ServerDeviceConnection.ts 6:0-53
     @ ./src/server/ServiceDeviceTracker.ts
     @ ./src/server/index.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ws-scrcpy@0.5.0 build:webpack: `webpack --config webpack.ws-scrcpy.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ws-scrcpy@0.5.0 build:webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jess.chu\AppData\Roaming\npm-cache\_logs\2020-10-08T10_14_17_594Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ws-scrcpy@0.5.0 dist: `npm run build:webpack && npm run copy:package.json && npm run copy:license`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ws-scrcpy@0.5.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jess.chu\AppData\Roaming\npm-cache\_logs\2020-10-08T10_14_17_637Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ws-scrcpy@0.5.0 start: `npm run dist && npm run start:dist`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ws-scrcpy@0.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jess.chu\AppData\Roaming\npm-cache\_logs\2020-10-08T10_14_17_670Z-debug.log
```

**Comment by drauggres** [comment] 2020-10-08 11:17
Hi. Can you run `npx webpack --config webpack.ws-scrcpy.config.js --display verbose` and share the output?

**Comment by drauggres** [comment] 2020-10-08 14:39
Also try to delete `package-lock.json` if you have one and reinstall node_modules with `npm install`.

**Comment by mtimti** [comment] 2020-10-13 11:27
I'm also facing the issue, i added the requested log and i also try to delete `package-lock.json`  and reinstalled node_modules with `npm` `install.`
[webpack.ws-scrcpy.config.js.log](https://github.com/NetrisTV/ws-scrcpy/files/5370981/webpack.ws-scrcpy.config.js.log)

**Comment by drauggres** [comment] 2020-10-13 11:45
Hi @mtimti, can you try `develop` branch?
Also what is your environment (os, node version)?

**Comment by drauggres** [comment] 2020-10-13 12:05
Should be fixed in `develop` (if the problem was on Windows).

**Comment by mtimti** [comment] 2020-10-13 12:38
Hi @drauggres, I'm sorry, the hotfix didn't helped, the issue is the same as on the master branch. i'm using 

- Windows Server 2016
- node v12.18.4

Thanks, mti

**Comment by drauggres** [comment] 2020-10-13 13:27
Now it definitely works on Windows.

**Comment by mtimti** [comment] 2020-10-13 13:42
thanks, i can confirm, the issue is solved

**Closed** 2020-10-14 11:35 UTC
